# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-25 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Runner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('alias', models.CharField(max_length=200)),
                ('sex', models.CharField(max_length=1)),
                ('birthdate', models.DateTimeField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modidification', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
