# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-01 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('max_runner_number', models.IntegerField()),
                ('max_time', models.DateTimeField()),
                ('price', models.FloatField()),
                ('path_url', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=10000)),
                ('date_start', models.DateTimeField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modidification', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
