# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-04 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_race'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='max_time',
            field=models.IntegerField(),
        ),
    ]
