# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-04 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20170304_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='distance_meter',
            field=models.IntegerField(default=10000),
            preserve_default=False,
        ),
    ]
