# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-04 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_race_distance_meter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_meter', models.IntegerField()),
                ('max_runner_number', models.IntegerField()),
                ('max_time', models.IntegerField()),
                ('price', models.FloatField()),
                ('path_url', models.CharField(max_length=1000)),
                ('date_start', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='race',
            name='distance_meter',
        ),
        migrations.RemoveField(
            model_name='race',
            name='max_runner_number',
        ),
        migrations.RemoveField(
            model_name='race',
            name='max_time',
        ),
        migrations.RemoveField(
            model_name='race',
            name='path_url',
        ),
        migrations.RemoveField(
            model_name='race',
            name='price',
        ),
        migrations.AddField(
            model_name='route',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Race'),
        ),
    ]
