# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-19 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20170319_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='facebook_page_url',
            field=models.URLField(default='', max_length=1000),
        ),
    ]
